elasticsearch-master:
  ports:
  - 9200:9200/tcp
  - 9300:9300/tcp
  environment:
    ES_HEAP_SIZE: 1g
  command:
  - elasticsearch
  - -Des.cluster.name=es-cluster
  - -Des.node.name=es01
  - -Des.node.master=true
  - -Des.node.data=false
  image: slamhan/elasticsearch:latest
elasticsearch2:
  environment:
    ES_HEAP_SIZE: 1g
  command:
  - elasticsearch
  - -Des.cluster.name=es-cluster
  - -Des.node.name=es02
  - -Des.discovery.zen.ping.unicast.hosts=elasticsearch-master
  image: slamhan/elasticsearch:latest
  links:
  - elasticsearch-master:elasticsearch-master
  volumes:
  - /opt/elasticsearch/data
elasticsearch1:
  environment:
    ES_HEAP_SIZE: 1g
  command:
  - elasticsearch
  - -Des.cluster.name=es-cluster
  - -Des.node.name=es03
  - -Des.discovery.zen.ping.unicast.hosts=elasticsearch-master
  image: slamhan/elasticsearch:latest
  links:
  - elasticsearch-master:elasticsearch-master
  volumes:
  - /opt/elasticsearch/data